#!/usr/bin/env node
/**
 * Rendered-page audit for the REDCELL Worker.
 *
 * Every page is assembled by string concatenation, so the failure mode that
 * matters is not "does the source parse" (node --check already covers that) but
 * "is the HTML we actually serve well-formed". This shipped once: an external
 *   <script src=...></script>
 * was folded into the inline script string, its closing tag terminated the inline
 * block early, and the rest of the page's JavaScript rendered as visible text.
 * node --check passed, pytest passed, and the page was still broken.
 *
 * Usage:  node tools/page_audit.mjs [baseUrl]
 *         node tools/page_audit.mjs http://127.0.0.1:8787
 */
const BASE = (process.argv[2] || 'https://redcell.redcellv1.workers.dev').replace(/\/$/, '');

/* Auditing /account needs a session, and creating one costs KV writes from the same small daily
   budget real users draw on. ACCOUNT_BASE points just that part at a local Worker — the HTML is
   generated by the same code, so the audit still means something, and it beats not auditing the
   signed-in pages at all, which is how a dead script survived eight rounds. */
const ACCOUNT_BASE = (process.env.ACCOUNT_BASE || BASE).replace(/\/$/, '');

/* Identify our own traffic so it can be kept out of the public counters at /stats.
   Wrapping fetch once is the only reliable way — a header added per call site is a header
   someone forgets at the next call site, and the counters go quietly wrong again. */
const _fetch = globalThis.fetch;
globalThis.fetch = async (url, opts = {}) => {
  // Retry belongs in the wrapper, not at each call site: this same transient-network crash was
  // fixed four times in a row, once per new fetch, before being put where new fetches inherit it.
  const withHeaders = { ...opts, headers: { 'User-Agent': 'redcell-verify/1', 'X-REDCELL-Synthetic': '1', ...(opts.headers || {}) } };
  let last;
  for (let i = 0; i < 3; i++) {
    try { return await _fetch(url, withHeaders); }
    catch (e) { last = e; await new Promise((r) => setTimeout(r, 500 * (i + 1))); }
  }
  throw last;
};

const PAGES = [
  '/', '/docs', '/agents', '/ci', '/mcp', '/quickstart', '/example', '/vs',
  '/methodology', '/changelog', '/benchmark', '/breach', '/pitch',
  '/signup', '/login', '/terms', '/privacy', '/refunds',
];

// Ground truth for the numbers the marketing copy quotes. A security product that
// advertises a detector count it does not have loses the argument before it starts;
// the landing said 37 while the code and /health said 38.
let TRUTH = null;
async function loadTruth() {
  try {
    const r = await fetch(BASE + '/health');
    const d = await r.json();
    TRUTH = { firewall: d.firewall_rules, statics: d.detectors, attacks: d.attacks };
  } catch (e) { TRUTH = null; }
}

const failures = [];
const notes = [];
function fail(page, msg) { failures.push(page + ': ' + msg); }

/** Inline <script> blocks, excluding <script src=...> which have no body. */
function inlineScripts(html) {
  const out = [];
  const re = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  let m;
  while ((m = re.exec(html))) {
    if (/\bsrc\s*=/i.test(m[1])) continue;
    out.push(m[2]);
  }
  return out;
}

/** Text the user can actually read, with script/style stripped out. */
function visibleText(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ');
}

async function get(url, cookie, tries = 3) {
  let last;
  for (let i = 0; i < tries; i++) {
    try {
      const r = await fetch(url, { redirect: 'manual', headers: cookie ? { Cookie: cookie } : {} });
      return { status: r.status, body: await r.text() };
    } catch (e) {
      last = e;
      await new Promise((r) => setTimeout(r, 400 * (i + 1)));
    }
  }
  throw last;
}

async function audit(page, cookie, origin) {
  let res, html;
  try {
    const r = await get((origin || BASE) + page, cookie);
    res = { status: r.status };
    html = r.body;
  } catch (e) {
    return fail(page, 'request failed: ' + e.message);
  }
  if (res.status !== 200) return fail(page, 'HTTP ' + res.status);

  // 1. the bug that shipped: a nested <script> inside an inline block
  for (const body of inlineScripts(html)) {
    if (/<script\b/i.test(body)) {
      fail(page, 'inline <script> block contains a nested <script> tag — the closing tag will end the block early');
    }
  }

  // 2. its symptom, caught independently: raw code visible as page text
  const text = visibleText(html);
  for (const marker of ['function q(i)', 'async function post(', 'document.getElementById(', 'Paddle.Checkout.open']) {
    if (text.includes(marker)) fail(page, 'raw JavaScript is rendered as page text (found "' + marker + '")');
  }

  // 3. unrendered template artifacts
  if (/\$\{[A-Za-z_]/.test(html)) fail(page, 'unrendered ${...} template placeholder in output');
  if (html.includes('undefined<') || html.includes('>undefined')) notes.push(page + ': literal "undefined" in output');

  // 4. tag balance for the elements we build by hand
  for (const tag of ['script', 'style', 'footer', 'header']) {
    const open = (html.match(new RegExp('<' + tag + '\\b', 'gi')) || []).length;
    const close = (html.match(new RegExp('</' + tag + '>', 'gi')) || []).length;
    if (open !== close) fail(page, '<' + tag + '> unbalanced: ' + open + ' open / ' + close + ' close');
  }

  // 5. the chrome every page is supposed to carry
  if (!html.includes('class=rf')) fail(page, 'shared footer missing');
  for (const l of ['/terms', '/privacy', '/refunds']) {
    if (!html.includes('href="' + l + '"')) fail(page, 'legal link ' + l + ' missing from footer');
  }

  // 6. quoted numbers must match what the code actually ships
  if (TRUTH) {
    const claims = [
      [/<b>(\d+)<\/b>\s*(?:&nbsp;)?\s*firewall detectors/g, TRUTH.firewall, 'firewall detectors'],
      [/(\d+)\s+detectors block injection/g, TRUTH.firewall, 'firewall detectors'],
      [/<b>(\d+)<\/b>\s*(?:&nbsp;)?\s*static checks/g, TRUTH.statics, 'static checks'],
    ];
    for (const [re, truth, what] of claims) {
      let m;
      while ((m = re.exec(html))) {
        if (Number(m[1]) !== truth) fail(page, 'claims ' + m[1] + ' ' + what + ' but the code ships ' + truth);
      }
    }
  }

  // 7. every inline script must actually PARSE.
  //     worker.js parsing says nothing about the JavaScript it emits into a page: the account
  //     page shipped a script with `style=\"color:...\"` inside a single-quoted JS string, so
  //     the quote closed the string early and the WHOLE script failed to parse. Nothing on that
  //     page worked — no key minting, no logout, no delete, and an Upgrade button that silently
  //     did nothing — for several rounds, while this audit passed because the HTML was fine.
  for (const m of html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi)) {
    const src = m[1];
    if (!src.trim()) continue;
    try {
      new Function(src);
    } catch (e) {
      fail(page, 'inline script does not parse (' + e.message + ') — nothing on this page will run');
    }
  }

  // 8. every element id the inline script reaches for must exist on the page.
  //     A mistyped or renamed id makes getElementById return null; the handler is never
  //     attached and the control silently does nothing — the same user-visible symptom as the
  //     parse error above, with none of the noise. Cheap to check statically, so check it.
  {
    const inline = [...html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi)]
      .map((m) => m[1]).join('\n');
    /* Only flag ids that are dereferenced IMMEDIATELY — q("x").onclick or getElementById("x").
       style. Those throw when the element is missing. Code that stores the lookup and null-checks
       it (var BUY = q("buy"); if (BUY) {...}) is correct and must not be flagged: /account
       renders the upgrade button only when billing is configured, so a local Worker legitimately
       has no #buy, and flagging that taught nothing. */
    const wanted = new Set();
    for (const m of inline.matchAll(/getElementById\(\s*["'`]([A-Za-z0-9_-]+)["'`]\s*\)\s*\./g)) wanted.add(m[1]);
    for (const m of inline.matchAll(/\bq\(\s*["'`]([A-Za-z0-9_-]+)["'`]\s*\)\s*\./g)) wanted.add(m[1]);
    const present = new Set([...html.matchAll(/\sid=["']?([A-Za-z0-9_-]+)["']?/g)].map((m) => m[1]));
    const missing = [...wanted].filter((id) => !present.has(id));
    if (missing.length) {
      fail(page, 'script reaches for element id(s) that do not exist: ' + missing.join(', ')
        + ' — dereferenced without a null check, so the handler will throw');
    }
  }

  // 9. the social preview must be a format the platforms will actually render.
  //     og:image pointed at an SVG for months; X, LinkedIn, Facebook, Slack and Discord all
  //     decline to render SVG, so every shared link appeared with no card. Nothing in the
  //     suite noticed, because the tag was present and the URL returned 200.
  //     A noindex page is deliberately out of search, so it is not required to carry a card —
  //     but if it does carry one, the format rule still applies.
  const og = /property="og:image" content="([^"]+)"/.exec(html);
  const noindex = /name=robots content="noindex"/.test(html);
  if (!og) { if (!noindex) fail(page, 'no og:image'); }
  else if (/\.svgs*$/i.test(og[1])) fail(page, 'og:image is an SVG; social platforms will not render it');
  else if (!ogChecked.has(og[1])) {
    ogChecked.add(og[1]);
    const r = await fetch(og[1]).catch(() => null);
    const ct = r && r.headers.get('content-type') || '';
    if (!r || r.status !== 200) fail(page, 'og:image does not resolve: ' + og[1]);
    else if (!/^image\/(png|jpeg|webp|gif)/.test(ct)) fail(page, 'og:image serves ' + ct + ', which social platforms will not render');
  }

  // 10. the old dark/red identity must be gone
  // the first sweep only listed the primary tokens, so tinted leftovers (a dark-red border,
  // a red wash behind a card) survived on five pages unnoticed. Check those too.
  for (const tok of ['0b0d12', 'ff3b46', '9aa4b6', 'eaedf4', '3a2030', '2a1918', 'ff5b64',
                     'rgba(255,59,70', 'rgba(255, 59, 70']) {
    if (html.includes(tok)) fail(page, 'legacy dark/red token ' + tok + ' still present');
  }
}

const ogChecked = new Set();   // fetch each distinct share image once, not once per page

const t0 = Date.now();
await loadTruth();
for (const p of PAGES) await audit(p);   // sequential: parallel bursts trip the edge

/* The signed-in pages had never been audited at all, and that is exactly where the damage was:
   /account shipped an inline script that failed to parse, so key minting, logout, delete and the
   Upgrade button were all dead — and this audit passed every run because an unauthenticated
   fetch of /account returns the sign-in shell, not the real page. Sign in with a throwaway
   account, audit the real thing, then delete it. */
{
  const email = 'pageaudit' + Math.floor(Date.now() / 1000) + '@example.org';
  const pass = 'Str0ng-Pass-9xQ';
  let cookie = '';
  try {
    const r = await fetch(ACCOUNT_BASE + '/auth/register', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password: pass }),
    });
    const setC = r.headers.get('set-cookie');
    if (r.status === 200 && setC) cookie = setC.split(';')[0];
  } catch (e) { /* handled below */ }

  if (!cookie) {
    notes.push('could not sign in, so the authenticated pages were NOT audited');
  } else {
    for (const p of ['/account']) await audit(p, cookie, ACCOUNT_BASE);
    if (ACCOUNT_BASE !== BASE) notes.push('/account audited against ' + ACCOUNT_BASE + ' (same code, no production writes)');
    // Confirm the cleanup instead of assuming it: one run's throwaway account survived, and
    // silently accumulating test accounts is how /admin stops showing real signups.
    let cleaned = false;
    try {
      const del = await fetch(ACCOUNT_BASE + '/auth/delete', {
        method: 'POST', headers: { 'Content-Type': 'application/json', Cookie: cookie },
        body: JSON.stringify({ password: pass }),
      });
      cleaned = del.status === 200;
    } catch (e) { /* reported below */ }
    if (!cleaned) fail('page_audit', 'could not delete its throwaway account ' + email + ' — delete it by hand');
  }
}

console.log('audited ' + PAGES.length + ' pages against ' + BASE + ' in ' + (Date.now() - t0) + 'ms');
if (notes.length) { console.log('\nnotes:'); notes.forEach((n) => console.log('  - ' + n)); }
if (failures.length) {
  console.log('\nFAIL (' + failures.length + '):');
  failures.forEach((f) => console.log('  x ' + f));
  process.exit(1);
}
console.log('PASS — all pages well-formed, chrome intact, no legacy tokens');
